name: CI for XAMPP Web Server 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # allow manual trigger

jobs:
  build:            #Collect website code from repositories.
    name: Build Stage - Checkout Repositories
    runs-on: self-hosted

    steps:
      - name: Checkout Repo A (current datta45516)    #cloning your repository
        uses: actions/checkout@v3

      - name: Checkout Repo B (PRIVATE_KEY via PUBLIC key)  #cloning ur private repo inside public repo
        uses: actions/checkout@v3
        with:
          repository: datta45516/devops
          ssh-key: ${{ secrets.PRIVATE_KEY }}    
          ref: main                                    # capturing source code from main branch of private repo
          path: web                                    #copy souce code inside "web"
          persist-credentials: false                   # by default PAT flase  
          ssh-strict: false                     # By default, Git tries to strictly verify the host key of github.com against the known_hosts file.

      - name: Archive Website Code          
        run: |
          tar -czf website.tar.gz -C web .      

      - name: Upload Website Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-code
          path: website.tar.gz

  deploy:
    name: Deploy Stage - Transfer to XAMPP Server
    runs-on: self-hosted
    needs: build                            #call the build Job here 

    steps:
      - name: Download Website Artifact
        uses: actions/download-artifact@v4
        with:
          name: website-code
          path: .

      - name: Extract Artifact
        run: |
          tar -xzf website.tar.gz
          
      - name: Upload Files to Staging Directory (no sudo needed)
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_RUNNERVM }}" > private_key.pem
          chmod 600 private_key.pem
          rm -rf .git .github web/.git web/.github
          scp -i private_key.pem -o StrictHostKeyChecking=no -r * \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/deploy/

      - name: Move Files into XAMPP htdocs (with sudo)
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "sudo mkdir -p /opt/lampp/htdocs && \
             sudo rm -rf /opt/lampp/htdocs/* && \
             sudo mv /home/${{ secrets.USERNAME }}/deploy/* /opt/lampp/htdocs/ && \
             sudo chown -R admin:admin /opt/lampp/htdocs && \
             sudo chmod -R 755 /opt/lampp/htdocs"

      - name: Restart Apache in XAMPP
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "sudo /opt/lampp/lampp restartapache"

  test:
    name: Test Stage - Validate Website
    runs-on: self-hosted
    needs: deploy

    steps:
     - name: Wait for Web Server
       run: sleep 10

     - name: Test Website on Remote Server
       run: |
         curl -IL http://${{ secrets.HOST }} | grep "200 OK" || exit 1
ifm-pepw-qpj
